# This file contains the information needed for Shopify to authenticate
# requests and edit/update your remote theme files.
#
# Remove the 'sample' part of the filename so it is just config.yml and enter in your specific development theme id from shopify admin.
#
#
# 1. Set up a private app (https://help.shopify.com/api/guides/api-credentials#generate-private-app-credentials)
#    with "Read and write" permissions for "Theme templates and theme assets".
# 2. Replace the required variables for each environment below.
#
# password, theme_id, and store variables are required.
#
# For more information on this config file:
#   Configuration variables | http://shopify.github.io/themekit/configuration/
#   Ignore patterns | http://shopify.github.io/themekit/ignores/

---
development:
  password: f6cce4ffc9cee294c8c5f80545021d46
  theme_id: "34456993838"
  store: code-challenge.myshopify.com
  ignore_files:
    - config/settings_data.json
